### PR TITLE
add login.html with tailwind css

### PR DESCRIPTION
**Pull request by HunterWilson1**
I made simple login/signup page that will need navbar when the design is made. The ids should also correlate correctly to the queryselectors in login.js. Frontend please edit as need be

### CODE REVIEW

**Comment by CKBoytGT** [comment]
Hi Hunter, can you please confirm that water.gif was either created from scratch by you or came from a public domain or free-for-commercial-use source? If you aren't sure, please link me to the source and I will confirm whether we have permission to use it. Thanks!

**Comment by HunterWilson1** [comment]
this is the link https://tenor.com/view/anime-water-aesthetic-gif-21923099  . I only put it there as an example for myself it does not have to be used

**Comment by CKBoytGT** [comment]
Please revise to use a public domain or otherwise legally sourced image. Thanks!

**Comment by HunterWilson1** [comment]
Okay! I'll fix that. I'm sorry

**Comment by CKBoytGT** [comment]
No need to apologize! Looks excellent btw.

**Comment by HunterWilson1** [comment]
I believe I have deleted the gif from the image folder. Thank you

**Review by CKBoytGT — APPROVED** [review]

**Pull request merged**
